package br.com.ucsal.util;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Logger;

public class DatabaseUtil {

	
    private static final String URL = "jdbc:hsqldb:mem:lojadb";
    private static final String USER = "sa";
    private static final String PASSWORD = "";
    private static final Logger logger = Logger.getLogger(DatabaseUtil.class.getName());


    public static void iniciarBanco() {
        try {
            Class.forName("org.hsqldb.jdbc.JDBCDriver");
            logger.info("Driver JDBC HSQLDB carregado com sucesso.");
        } catch (ClassNotFoundException e) {
            logger.severe("Erro ao carregar o driver JDBC: " + e.getMessage());
            throw new RuntimeException("Driver JDBC não encontrado.", e);
        }

        try (Connection conn = DriverManager.getConnection(URL, USER, PASSWORD);
             Statement stmt = conn.createStatement()) {

            // Criação da tabela
            stmt.executeUpdate("CREATE TABLE produtos (" +
                    "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "nome VARCHAR(50), " +
                    "preco DOUBLE" +
                    ")");

            // Inserção de dados iniciais
            stmt.executeUpdate("INSERT INTO produtos (nome, preco) VALUES ('Notebook', 3500.00);");
            stmt.executeUpdate("INSERT INTO produtos (nome, preco) VALUES ('Smartphone', 1500.00);");

            logger.info("Banco de dados inicializado com sucesso!");

        } catch (SQLException e) {
            logger.severe("Erro ao inicializar o banco de dados: " + e.getMessage());
            throw new RuntimeException("Erro ao configurar o banco de dados.", e);
        }
    }

    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }

    
    
    
}

